apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  clusterIP: 10.39.240.114
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080

